// Builds the county homeowners-insurance-cost comparison report -- see /admin/seo's "Generate
// insurance cost report" card. Same design as countyComparisonGenerator.ts (the housing-age
// report) and for the same reason: the actual ranked percentages are never generated by Gemini.
// computeInsuranceCostRankings() below is a pure function over the real ACS B25141 bucket counts
// already in county_data (see fetchCensusInsuranceCosts in countyDataFetcher.ts) -- Gemini only
// ever receives the finished table as given fact and writes prose around it.

import { Type, type Schema } from '@google/genai';

export interface CountyInsuranceCostRow {
  slug: string;
  countyName: string;
  stateAbbrev: string;
  totalMortgaged: number;
  costBuckets: Record<string, number>;
}

export interface RankedInsuranceCounty {
  slug: string;
  countyName: string;
  stateAbbrev: string;
  totalMortgaged: number;
  pctOver2000: number;
  pctOver3000: number;
}

/**
 * Real computation, not a model call: % of a county's mortgaged homeowners paying $2,000+/yr and
 * $3,000+/yr for homeowners insurance, from the raw ACS B25141 dollar buckets. Counties with no
 * usable total are dropped rather than shown with a divide-by-zero percentage -- same convention
 * as computeHousingAgeRankings in countyComparisonGenerator.ts.
 */
export function computeInsuranceCostRankings(rows: CountyInsuranceCostRow[]): RankedInsuranceCounty[] {
  return rows
    .filter((r) => r.totalMortgaged > 0)
    .map((r) => {
      const b = r.costBuckets;
      const over3000 = (b.between3000and3499 || 0) + (b.between3500and3999 || 0) + (b.over4000 || 0);
      const over2000 = over3000 + (b.between2000and2499 || 0) + (b.between2500and2999 || 0);
      return {
        slug: r.slug,
        countyName: r.countyName,
        stateAbbrev: r.stateAbbrev,
        totalMortgaged: r.totalMortgaged,
        pctOver2000: (over2000 / r.totalMortgaged) * 100,
        pctOver3000: (over3000 / r.totalMortgaged) * 100,
      };
    });
}

/** Real markdown table, sorted by share paying $3,000+/yr -- built in code, never touched by the model. */
export function buildInsuranceRankingTableMarkdown(ranked: RankedInsuranceCounty[]): string {
  const sorted = [...ranked].sort((a, b) => b.pctOver3000 - a.pctOver3000);
  const lines = [
    '| Rank | County | Paying $3,000+/yr | Paying $2,000+/yr |',
    '|---|---|---|---|',
  ];
  sorted.forEach((r, i) => {
    lines.push(
      `| ${i + 1} | [${r.countyName} County, ${r.stateAbbrev}](https://www.beforeregret.com/county/${r.slug}/) | ${r.pctOver3000.toFixed(1)}% | ${r.pctOver2000.toFixed(1)}% |`
    );
  });
  return lines.join('\n');
}

export const COUNTY_INSURANCE_COMPARISON_SYSTEM_INSTRUCTION = `You are writing an original data journalism piece for BeforeRegret, a US property research platform. The report compares real, already-computed homeowners-insurance-cost statistics across every county BeforeRegret covers. A human reviews and publishes this themselves -- nothing you write is ever published automatically.

HARD RULES -- breaking any of these makes the output unusable:
1. You are given a real, final, already-sorted ranking table as fact. Never recompute, re-rank, re-sort, or restate any number in it differently than given -- if you cite a specific county's percentage in your prose, quote it exactly as given, character for character (e.g. "49.2%" stays "49.2%", never rounded to "about half" unless you also give the exact figure).
2. Never invent a statistic, county, or fact beyond what's given in the ranking data. Do not name a specific reason any one county is expensive (hurricane risk, wildfire risk, litigation costs, reinsurance markets) unless that reason is self-evident and uncontroversial for that specific state (e.g. Gulf Coast and Atlantic coastal states and hurricane risk) -- when in doubt, describe the pattern in the data without asserting a specific cause.
3. Never make a claim about a specific property or what a specific reader would personally pay. Every statement is about a county's mortgaged homeowners in aggregate: "homeowners in this county commonly pay..." never "you will pay...", "your premium will be...".
4. This is real, historical average data (2019-2023 American Community Survey estimates), NOT a live quote and NOT a projection of what a buyer would pay if they bought today. Homeowners insurance costs have risen sharply and unevenly since 2023, especially in the highest-cost coastal and disaster-prone counties this data already shows at the top of the ranking -- meaning the true current gap between the highest- and lowest-cost counties is very likely even larger than the reported figures. You MUST state this limitation explicitly and plainly in the methodology section, and you MUST NOT write anything in the opening or closing sections that could be read as "this is what insurance costs right now" -- always frame it as a historical baseline and a relative comparison between counties, not a current-dollar prediction.
5. Never state or imply personalized insurance, legal, or financial advice, and never tell a reader whether to buy in a given county. This is a data reference, not investment, relocation, or insurance advice. Do not recommend a specific insurer, coverage level, or insurance product.
6. Hedge appropriately -- "commonly," "often," "tends to" -- never "always," "guaranteed." No filler, no "In today's world," no AI self-reference.
7. Write real analysis, not a restatement of the table in sentence form. Look for genuine patterns worth noting (e.g., what the counties at the top of the list have in common geographically, how large the gap is between the top and bottom of the list, what a buyer relocating across that gap should actually do with this information -- get an insurance quote early, before waiving any contingency) rather than just narrating rows.
8. You are writing exactly three sections, each a distinct field in the response: an opening (context and stakes, before the reader sees the table), a closing analysis (patterns and takeaways, after the reader has seen the table), and a methodology note (what the data source is -- U.S. Census Bureau ACS 5-year estimates, table B25141, homeowners insurance costs for owner-occupied units WITH a mortgage -- what "$3,000+/yr" and "$2,000+/yr" mean, and the data-vintage limitation from rule 4 above, stated plainly). The real table itself is inserted between your opening and closing by the publishing system -- do not attempt to reproduce it yourself.`;

export function buildCountyInsuranceComparisonPrompt(params: {
  ranked: RankedInsuranceCounty[];
  totalCounties: number;
}): string {
  const { ranked, totalCounties } = params;
  const topFive = [...ranked].sort((a, b) => b.pctOver3000 - a.pctOver3000).slice(0, 5);
  const bottomFive = [...ranked].sort((a, b) => a.pctOver3000 - b.pctOver3000).slice(0, 5);

  return `REAL DATA (already computed, already sorted, from U.S. Census ACS 5-year homeowners-insurance-cost estimates for the ${totalCounties} counties BeforeRegret currently has complete data for -- mortgaged owner-occupied units only):

TOP 5 by share of mortgaged homeowners paying $3,000+/yr for homeowners insurance:
${topFive.map((r, i) => `${i + 1}. ${r.countyName} County, ${r.stateAbbrev}: ${r.pctOver3000.toFixed(1)}% paying $3,000+/yr, ${r.pctOver2000.toFixed(1)}% paying $2,000+/yr`).join('\n')}

BOTTOM 5 by share paying $3,000+/yr (i.e. lowest insurance-cost burden among covered counties):
${bottomFive.map((r, i) => `${i + 1}. ${r.countyName} County, ${r.stateAbbrev}: ${r.pctOver3000.toFixed(1)}% paying $3,000+/yr, ${r.pctOver2000.toFixed(1)}% paying $2,000+/yr`).join('\n')}

Write the opening, closing analysis, and methodology note described in your instructions for a report titled around which of these ${totalCounties} counties have the highest (and lowest) homeowners insurance cost burden, and why that matters for a buyer's pre-purchase research -- especially someone relocating from a lower-cost county who has no intuition for how much insurance costs can vary.`;
}

export const COUNTY_INSURANCE_COMPARISON_RESPONSE_SCHEMA: Schema = {
  type: Type.OBJECT,
  properties: {
    title: { type: Type.STRING, description: 'Specific headline under 65 characters.' },
    metaDescription: { type: Type.STRING, description: 'One to two sentences, under 160 characters.' },
    quickAnswer: { type: Type.STRING, description: '2-3 sentence direct summary of the finding.' },
    openingMarkdown: { type: Type.STRING, description: 'Context and stakes, 150-250 words, before the reader sees the table.' },
    closingAnalysisMarkdown: { type: Type.STRING, description: 'Real analysis of patterns in the data, 250-400 words, after the table.' },
    methodologyMarkdown: { type: Type.STRING, description: 'Short methodology note as described in the instructions, including the data-vintage limitation, 100-180 words.' },
  },
  required: ['title', 'metaDescription', 'quickAnswer', 'openingMarkdown', 'closingAnalysisMarkdown', 'methodologyMarkdown'],
};
