// Builds "original data journalism" reports comparing real federal data across every county
// BeforeRegret covers -- see /admin/seo's "Generate comparison report" button. The distinguishing
// design choice here versus every other generator in this codebase: the actual ranked numbers are
// never generated by Gemini at all. computeHousingAgeRankings() below is a pure function over the
// real Census data already in county_data -- Gemini only ever receives the finished table as
// given fact and writes prose around it. This is a stricter version of the anti-fabrication
// pattern the rest of the app already follows (never invent a stat) -- here, the model isn't even
// trusted to reproduce a real stat correctly in its own words without a chance of transcription
// drift, so the table itself is asserted, not requested.

import { Type, type Schema } from '@google/genai';

export interface CountyHousingAgeRow {
  slug: string;
  countyName: string;
  stateAbbrev: string;
  totalUnits: number;
  yearBuiltBuckets: Record<string, number>;
}

export interface RankedCounty {
  slug: string;
  countyName: string;
  stateAbbrev: string;
  totalUnits: number;
  pctBefore1950: number;
  pctBefore1980: number;
}

/**
 * Real computation, not a model call: % of a county's housing stock built before 1950 (the era of
 * knob-and-tube wiring, galvanized supply piping, cast-iron sewer lines -- see
 * engine/inspectionPriorities.ts's own rules for these, which use the same real thresholds) and
 * before 1980 (covers the 1978 federal lead-paint cutoff -- rounded up to the nearest Census
 * decade bucket boundary rather than claiming false decade-level precision at exactly 1978).
 * Counties with no usable total are dropped rather than shown with a divide-by-zero percentage.
 */
export function computeHousingAgeRankings(rows: CountyHousingAgeRow[]): RankedCounty[] {
  return rows
    .filter((r) => r.totalUnits > 0)
    .map((r) => {
      const b = r.yearBuiltBuckets;
      const before1950 = (b.built1939OrEarlier || 0) + (b.built1940to1949 || 0);
      const before1980 = before1950 + (b.built1950to1959 || 0) + (b.built1960to1969 || 0) + (b.built1970to1979 || 0);
      return {
        slug: r.slug,
        countyName: r.countyName,
        stateAbbrev: r.stateAbbrev,
        totalUnits: r.totalUnits,
        pctBefore1950: (before1950 / r.totalUnits) * 100,
        pctBefore1980: (before1980 / r.totalUnits) * 100,
      };
    });
}

/** Real markdown table, sorted by the given metric -- built in code, never touched by the model. */
export function buildRankingTableMarkdown(
  ranked: RankedCounty[],
  sortBy: 'pctBefore1950' | 'pctBefore1980'
): string {
  const sorted = [...ranked].sort((a, b) => b[sortBy] - a[sortBy]);
  const otherCol = sortBy === 'pctBefore1950' ? 'pctBefore1980' : 'pctBefore1950';
  const header = sortBy === 'pctBefore1950'
    ? '| Rank | County | Built before 1950 | Built before 1980 |'
    : '| Rank | County | Built before 1980 | Built before 1950 |';
  const lines = [header, '|---|---|---|---|'];
  sorted.forEach((r, i) => {
    const primary = r[sortBy].toFixed(1);
    const secondary = r[otherCol].toFixed(1);
    lines.push(`| ${i + 1} | [${r.countyName} County, ${r.stateAbbrev}](https://www.beforeregret.com/county/${r.slug}/) | ${primary}% | ${secondary}% |`);
  });
  return lines.join('\n');
}

export const COUNTY_COMPARISON_SYSTEM_INSTRUCTION = `You are writing an original data journalism piece for BeforeRegret, a US property research platform. The report compares real, already-computed housing-age statistics across every county BeforeRegret covers. A human reviews and publishes this themselves -- nothing you write is ever published automatically.

HARD RULES -- breaking any of these makes the output unusable:
1. You are given a real, final, already-sorted ranking table as fact. Never recompute, re-rank, re-sort, or restate any number in it differently than given -- if you cite a specific county's percentage in your prose, quote it exactly as given, character for character (e.g. "55.6%" stays "55.6%", never rounded to "56%" or generalized to "over half").
2. Never invent a statistic, county, or fact beyond what's given in the ranking data. If you want to make a general point about why older housing matters (knob-and-tube wiring, galvanized pipe, lead paint), use only the well-established public facts already established elsewhere on this site: lead-based paint disclosure applies to homes built before 1978 (federal law), knob-and-tube wiring was standard before roughly 1950, galvanized steel supply piping was common before roughly 1970. Don't invent additional eras or materials not in that list.
3. Never make a claim about a specific property. Every statement is about a county's housing stock in aggregate: "homes in this county commonly..." never "a specific home has...".
4. Never state or imply personalized insurance, legal, or financial advice, and never tell a reader whether to buy in a given county. This is a data reference, not investment or relocation advice.
5. Hedge appropriately -- "commonly," "often," "tends to" -- never "always," "guaranteed." No filler, no "In today's world," no AI self-reference.
6. Write real analysis, not a restatement of the table in sentence form. Look for genuine patterns worth noting (e.g., what the counties at the top of the list have in common, how large the gap is between the top and bottom of the list, what the data does and doesn't tell a reader) rather than just narrating rows.
7. You are writing exactly three sections, each a distinct field in the response: an opening (context and stakes, before the reader sees the table), a closing analysis (patterns and takeaways, after the reader has seen the table), and a methodology note (what the data source is, what "before 1950" and "before 1980" mean and why those specific years, and the honest limitation that Census reports housing age in decade buckets, so "before 1980" is the nearest clean decade boundary above the real 1978 legal cutoff, not the exact year). The real table itself is inserted between your opening and closing by the publishing system -- do not attempt to reproduce it yourself.`;

export function buildCountyComparisonPrompt(params: {
  rankedByPre1950: RankedCounty[];
  totalCounties: number;
}): string {
  const { rankedByPre1950, totalCounties } = params;
  const topFive = [...rankedByPre1950].sort((a, b) => b.pctBefore1950 - a.pctBefore1950).slice(0, 5);
  const bottomFive = [...rankedByPre1950].sort((a, b) => a.pctBefore1950 - b.pctBefore1950).slice(0, 5);

  return `REAL DATA (already computed, already sorted, from U.S. Census ACS 5-year housing-age estimates for the ${totalCounties} counties BeforeRegret currently covers with complete verified data):

TOP 5 by share of housing built before 1950:
${topFive.map((r, i) => `${i + 1}. ${r.countyName} County, ${r.stateAbbrev}: ${r.pctBefore1950.toFixed(1)}% before 1950, ${r.pctBefore1980.toFixed(1)}% before 1980`).join('\n')}

BOTTOM 5 by share of housing built before 1950 (i.e. newest housing stock among covered counties):
${bottomFive.map((r, i) => `${i + 1}. ${r.countyName} County, ${r.stateAbbrev}: ${r.pctBefore1950.toFixed(1)}% before 1950, ${r.pctBefore1980.toFixed(1)}% before 1980`).join('\n')}

Write the opening, closing analysis, and methodology note described in your instructions for a report titled around which of these ${totalCounties} counties have the oldest (and newest) housing stock, and why that matters for a buyer's inspection and insurance research.`;
}

export const COUNTY_COMPARISON_RESPONSE_SCHEMA: Schema = {
  type: Type.OBJECT,
  properties: {
    title: { type: Type.STRING, description: 'Specific headline under 65 characters.' },
    metaDescription: { type: Type.STRING, description: 'One to two sentences, under 160 characters.' },
    quickAnswer: { type: Type.STRING, description: '2-3 sentence direct summary of the finding.' },
    openingMarkdown: { type: Type.STRING, description: 'Context and stakes, 150-250 words, before the reader sees the table.' },
    closingAnalysisMarkdown: { type: Type.STRING, description: 'Real analysis of patterns in the data, 250-400 words, after the table.' },
    methodologyMarkdown: { type: Type.STRING, description: 'Short methodology note as described in the instructions, 80-150 words.' },
  },
  required: ['title', 'metaDescription', 'quickAnswer', 'openingMarkdown', 'closingAnalysisMarkdown', 'methodologyMarkdown'],
};
