# Measures every image an article can declare, and writes src/data/imageDimensions.ts.
#
#   python3 scripts/measure-images.py            # dry run
#   APPLY=1 python3 scripts/measure-images.py
#
# WHY A GENERATED MODULE AND NOT A FILE READ. Article schema is emitted from two places --
# scripts/prerender-guides.tsx at build time and src/components/seo/GuidePageView.tsx in the
# browser -- and src/utils/articleImage.ts is shared between them on purpose, because those two
# have drifted before. The browser half cannot read a JSON file off disk, so the dimensions have to
# arrive as an importable module. Generating it keeps the numbers measured rather than typed.
#
# WHY DIMENSIONS AT ALL. schema.org ImageObject takes width and height, and Google's structured
# data documentation asks for images that are crawlable and indexable with their size declared.
# A bare URL string is valid and says less.
import os
from pathlib import Path
from PIL import Image

APPLY = os.environ.get("APPLY") == "1"
ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUT = ROOT / "src" / "data" / "imageDimensions.ts"

# Everything an article can point at: the body diagrams, plus the sitewide fallback.
TARGETS = sorted(PUBLIC.glob("images/*.webp")) + sorted(PUBLIC.glob("images/*.jpg")) + [PUBLIC / "hero-bg.jpg"]


def main():
    rows = []
    for p in TARGETS:
        if not p.exists():
            print(f"  skip (missing): {p.relative_to(PUBLIC)}")
            continue
        with Image.open(p) as im:
            w, h = im.size
        rel = "/" + str(p.relative_to(PUBLIC))
        rows.append((rel, w, h))
        print(f"  {rel:<52} {w}x{h}   {w/h:.2f}:1")

    if not rows:
        raise SystemExit("ABORT: measured nothing")

    body = "".join(f"  '{r}': {{ width: {w}, height: {h} }},\n" for r, w, h in rows)
    ts = f"""// GENERATED by scripts/measure-images.py -- do not edit by hand.
//
// Pixel dimensions for every image an article can declare in its schema. Generated rather than
// typed because a hand-written height is a number nobody re-checks when an image is replaced, and
// a wrong one in ImageObject is worse than none.
//
// Imported by src/utils/articleImage.ts, which is shared by the prerender and the client component
// so the static HTML and the hydrated page cannot disagree about what represents the article.
//
// Re-run after adding or replacing anything in public/images/:
//   APPLY=1 python3 scripts/measure-images.py

export interface ImageDimensions {{ width: number; height: number }}

export const IMAGE_DIMENSIONS: Record<string, ImageDimensions> = {{
{body}}};
"""
    if not APPLY:
        print(f"\n  would write {OUT.relative_to(ROOT)} with {len(rows)} entries")
        print("  DRY RUN -- nothing written.\n")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(ts, encoding="utf8")
    print(f"\n  wrote {OUT.relative_to(ROOT)}  ({len(rows)} images)")


if __name__ == "__main__":
    main()
