// GENERATED by scripts/measure-images.py -- do not edit by hand.
//
// Pixel dimensions for every image an article can declare in its schema. Generated rather than
// typed because a hand-written height is a number nobody re-checks when an image is replaced, and
// a wrong one in ImageObject is worse than none.
//
// Imported by src/utils/articleImage.ts, which is shared by the prerender and the client component
// so the static HTML and the hydrated page cannot disagree about what represents the article.
//
// Re-run after adding or replacing anything in public/images/:
//   APPLY=1 python3 scripts/measure-images.py

export interface ImageDimensions { width: number; height: number }

export const IMAGE_DIMENSIONS: Record<string, ImageDimensions> = {
  '/images/county-vs-city-permit-jurisdiction.webp': { width: 1600, height: 900 },
  '/images/eifs-vs-traditional-stucco-wall-cross-section.webp': { width: 1600, height: 995 },
  '/images/fruitful-home-cover-lg.webp': { width: 520, height: 832 },
  '/images/fruitful-home-cover.webp': { width: 300, height: 480 },
  '/images/knob-and-tube-vs-modern-sheathed-cable.webp': { width: 1600, height: 995 },
  '/images/open-ground-vs-bootleg-ground-receptacle-wiring.webp': { width: 1600, height: 873 },
  '/images/polybutylene-vs-pex-pipe-identification.webp': { width: 1600, height: 995 },
  '/images/single-strand-aluminum-vs-copper-wiring-identification.webp': { width: 1600, height: 900 },
  '/images/fruitful-home-cover-lg.jpg': { width: 520, height: 832 },
  '/images/fruitful-home-cover.jpg': { width: 300, height: 480 },
  '/hero-bg.jpg': { width: 1895, height: 830 },
};
